---
default:
  interface_suffix: Mock
items:
- src:
    file: internal/domain/filesystem.go
    interface: FileSystem
  dest:
    package: test
    file: internal/test/filesystem_mock.go
- src:
    dir: internal/domain
    interface: CfgReader
  dest:
    package: test
    file: internal/test/cfg_reader_mock.go
- src:
    package: io
    interface: WriteCloser
  dest:
    package: test
    file: internal/test/write_closer_mock.go
