package examples

// Don't edit this file.
// This file is generated by gomic 0.1.0.
// https://github.com/suzuki-shunsuke/gomic

import (
	testing "testing"

	gomic "github.com/suzuki-shunsuke/gomic/gomic"
	"github.com/suzuki-shunsuke/rterror"
)

type (
	// HelloMock11 is a mock.
	HelloMock11 struct {
		t                      *testing.T
		name                   string
		CallbackNotImplemented func(t *testing.T, intfName, methodName string)
		Impl                   HelloMock11Impl
	}

	// HelloMock11Impl holds functions which implement interface's methods.
	HelloMock11Impl struct {
		Hello func() rterror.RuntimeError
	}
)

// NewHelloMock11 returns HelloMock11 .
func NewHelloMock11(t *testing.T) *HelloMock11 {
	return &HelloMock11{t: t}
}

// Hello is a mock method.
func (mock HelloMock11) Hello() rterror.RuntimeError {
	methodName := "Hello" // nolint: goconst
	if mock.Impl.Hello != nil {
		return mock.Impl.Hello()
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeHello()
}

// FakeHello is a fake method.
func (mock HelloMock11) FakeHello() rterror.RuntimeError {
	var (
		r0 rterror.RuntimeError
	)
	return r0
}
