package examples

// Don't edit this file.
// This file is generated by gomic 0.1.0.
// https://github.com/suzuki-shunsuke/gomic

import (
	"go/ast"
	"io"
	"os"
	testing "testing"

	gomic "github.com/suzuki-shunsuke/gomic/gomic"
)

type (
	// HelloMock9 is a mock.
	HelloMock9 struct {
		t                      *testing.T
		name                   string
		CallbackNotImplemented func(t *testing.T, intfName, methodName string)
		Impl                   HelloMock9Impl
	}

	// HelloMock9Impl holds functions which implement interface's methods.
	HelloMock9Impl struct {
		Hello  func(p0 *ast.File) map[io.Reader]os.File
		Hello2 func() func() string
		Hello3 func() struct{}
	}
)

// NewHelloMock9 returns HelloMock9 .
func NewHelloMock9(t *testing.T) *HelloMock9 {
	return &HelloMock9{t: t}
}

// Hello is a mock method.
func (mock HelloMock9) Hello(p0 *ast.File) map[io.Reader]os.File {
	methodName := "Hello" // nolint: goconst
	if mock.Impl.Hello != nil {
		return mock.Impl.Hello(p0)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeHello(p0)
}

// FakeHello is a fake method.
func (mock HelloMock9) FakeHello(p0 *ast.File) map[io.Reader]os.File {
	var (
		r0 map[io.Reader]os.File
	)
	return r0
}

// Hello2 is a mock method.
func (mock HelloMock9) Hello2() func() string {
	methodName := "Hello2" // nolint: goconst
	if mock.Impl.Hello2 != nil {
		return mock.Impl.Hello2()
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeHello2()
}

// FakeHello2 is a fake method.
func (mock HelloMock9) FakeHello2() func() string {
	var (
		r0 func() string
	)
	return r0
}

// Hello3 is a mock method.
func (mock HelloMock9) Hello3() struct{} {
	methodName := "Hello3" // nolint: goconst
	if mock.Impl.Hello3 != nil {
		return mock.Impl.Hello3()
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeHello3()
}

// FakeHello3 is a fake method.
func (mock HelloMock9) FakeHello3() struct{} {
	var (
		r0 struct{}
	)
	return r0
}
