package examples

// Don't edit this file.
// This file is generated by gomic 0.1.0.
// https://github.com/suzuki-shunsuke/gomic

import (
	testing "testing"

	examples0 "github.com/suzuki-shunsuke/gomic/examples/examples"
	"github.com/suzuki-shunsuke/gomic/examples/examples/examples"
	gomic "github.com/suzuki-shunsuke/gomic/gomic"
)

type (
	// HelloMock7 is a mock.
	HelloMock7 struct {
		t                      *testing.T
		name                   string
		CallbackNotImplemented func(t *testing.T, intfName, methodName string)
		Impl                   HelloMock7Impl
	}

	// HelloMock7Impl holds functions which implement interface's methods.
	HelloMock7Impl struct {
		Read  func(p []byte) (n int, err error)
		Foo   func() examples.ChildFoo
		Child func() examples0.ChildHello
	}
)

// NewHelloMock7 returns HelloMock7 .
func NewHelloMock7(t *testing.T) *HelloMock7 {
	return &HelloMock7{t: t}
}

// Read is a mock method.
func (mock HelloMock7) Read(p []byte) (n int, err error) {
	methodName := "Read" // nolint: goconst
	if mock.Impl.Read != nil {
		return mock.Impl.Read(p)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeRead(p)
}

// FakeRead is a fake method.
func (mock HelloMock7) FakeRead(p []byte) (n int, err error) {
	return n, err
}

// Foo is a mock method.
func (mock HelloMock7) Foo() examples.ChildFoo {
	methodName := "Foo" // nolint: goconst
	if mock.Impl.Foo != nil {
		return mock.Impl.Foo()
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeFoo()
}

// FakeFoo is a fake method.
func (mock HelloMock7) FakeFoo() examples.ChildFoo {
	var (
		r0 examples.ChildFoo
	)
	return r0
}

// Child is a mock method.
func (mock HelloMock7) Child() examples0.ChildHello {
	methodName := "Child" // nolint: goconst
	if mock.Impl.Child != nil {
		return mock.Impl.Child()
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeChild()
}

// FakeChild is a fake method.
func (mock HelloMock7) FakeChild() examples0.ChildHello {
	var (
		r0 examples0.ChildHello
	)
	return r0
}
