package examples

// Don't edit this file.
// This file is generated by gomic 0.1.0.
// https://github.com/suzuki-shunsuke/gomic

import (
	testing "testing"

	gomic "github.com/suzuki-shunsuke/gomic/gomic"
)

type (
	// HelloMock2 is a mock.
	HelloMock2 struct {
		t                      *testing.T
		name                   string
		CallbackNotImplemented func(t *testing.T, intfName, methodName string)
		Impl                   HelloMock2Impl
	}

	// HelloMock2Impl holds functions which implement interface's methods.
	HelloMock2Impl struct {
		Foo  func(bar Bar) string
		Read func(p []byte) (n int, err error)
	}
)

// NewHelloMock2 returns HelloMock2 .
func NewHelloMock2(t *testing.T) *HelloMock2 {
	return &HelloMock2{t: t}
}

// Foo is a mock method.
func (mock HelloMock2) Foo(bar Bar) string {
	methodName := "Foo" // nolint: goconst
	if mock.Impl.Foo != nil {
		return mock.Impl.Foo(bar)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeFoo(bar)
}

// FakeFoo is a fake method.
func (mock HelloMock2) FakeFoo(bar Bar) string {
	var (
		r0 string
	)
	return r0
}

// Read is a mock method.
func (mock HelloMock2) Read(p []byte) (n int, err error) {
	methodName := "Read" // nolint: goconst
	if mock.Impl.Read != nil {
		return mock.Impl.Read(p)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeRead(p)
}

// FakeRead is a fake method.
func (mock HelloMock2) FakeRead(p []byte) (n int, err error) {
	return n, err
}
