package examples

// Don't edit this file.
// This file is generated by gomic 0.1.0.
// https://github.com/suzuki-shunsuke/gomic

import (
	"go/types"
	testing "testing"

	gomic "github.com/suzuki-shunsuke/gomic/gomic"
)

type (
	// HelloMock8 is a mock.
	HelloMock8 struct {
		t                      *testing.T
		name                   string
		CallbackNotImplemented func(t *testing.T, intfName, methodName string)
		Impl                   HelloMock8Impl
	}

	// HelloMock8Impl holds functions which implement interface's methods.
	HelloMock8Impl struct {
		Tuple func() *types.Tuple
	}
)

// NewHelloMock8 returns HelloMock8 .
func NewHelloMock8(t *testing.T) *HelloMock8 {
	return &HelloMock8{t: t}
}

// Tuple is a mock method.
func (mock HelloMock8) Tuple() *types.Tuple {
	methodName := "Tuple" // nolint: goconst
	if mock.Impl.Tuple != nil {
		return mock.Impl.Tuple()
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeTuple()
}

// FakeTuple is a fake method.
func (mock HelloMock8) FakeTuple() *types.Tuple {
	var (
		r0 *types.Tuple
	)
	return r0
}
