package examples

// Don't edit this file.
// This file is generated by gomic 0.1.0.
// https://github.com/suzuki-shunsuke/gomic

import (
	testing "testing"

	gomic "github.com/suzuki-shunsuke/gomic/gomic"
)

type (
	// HelloMock5 is a mock.
	HelloMock5 struct {
		t                      *testing.T
		name                   string
		CallbackNotImplemented func(t *testing.T, intfName, methodName string)
		Impl                   HelloMock5Impl
	}

	// HelloMock5Impl holds functions which implement interface's methods.
	HelloMock5Impl struct {
		ExistFile func(p0 string) bool
		MkdirAll  func(p0 string)
	}
)

// NewHelloMock5 returns HelloMock5 .
func NewHelloMock5(t *testing.T) *HelloMock5 {
	return &HelloMock5{t: t}
}

// ExistFile is a mock method.
func (mock HelloMock5) ExistFile(p0 string) bool {
	methodName := "ExistFile" // nolint: goconst
	if mock.Impl.ExistFile != nil {
		return mock.Impl.ExistFile(p0)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeExistFile(p0)
}

// FakeExistFile is a fake method.
func (mock HelloMock5) FakeExistFile(p0 string) bool {
	var (
		r0 bool
	)
	return r0
}

// MkdirAll is a mock method.
func (mock HelloMock5) MkdirAll(p0 string) {
	methodName := "MkdirAll" // nolint: goconst
	if mock.Impl.MkdirAll != nil {
		mock.Impl.MkdirAll(p0)
		return
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	mock.FakeMkdirAll(p0)
}

// FakeMkdirAll is a fake method.
func (mock HelloMock5) FakeMkdirAll(p0 string) {
}
