package examples

// Don't edit this file.
// This file is generated by gomic 0.1.0.
// https://github.com/suzuki-shunsuke/gomic

import (
	testing "testing"

	gomic "github.com/suzuki-shunsuke/gomic/gomic"
)

type (
	// HelloMock12 is a mock.
	HelloMock12 struct {
		t                      *testing.T
		name                   string
		CallbackNotImplemented func(t *testing.T, intfName, methodName string)
		Impl                   HelloMock12Impl
	}

	// HelloMock12Impl holds functions which implement interface's methods.
	HelloMock12Impl struct {
		Param func() interface{}
		Error func() string
	}
)

// NewHelloMock12 returns HelloMock12 .
func NewHelloMock12(t *testing.T) *HelloMock12 {
	return &HelloMock12{t: t}
}

// Param is a mock method.
func (mock HelloMock12) Param() interface{} {
	methodName := "Param" // nolint: goconst
	if mock.Impl.Param != nil {
		return mock.Impl.Param()
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeParam()
}

// FakeParam is a fake method.
func (mock HelloMock12) FakeParam() interface{} {
	var (
		r0 interface{}
	)
	return r0
}

// Error is a mock method.
func (mock HelloMock12) Error() string {
	methodName := "Error" // nolint: goconst
	if mock.Impl.Error != nil {
		return mock.Impl.Error()
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeError()
}

// FakeError is a fake method.
func (mock HelloMock12) FakeError() string {
	var (
		r0 string
	)
	return r0
}
