package examples

// Don't edit this file.
// This file is generated by gomic 0.1.0.
// https://github.com/suzuki-shunsuke/gomic

import (
	"io"
	"mime/multipart"
	"net/http"
	"net/url"
	testing "testing"

	echo "github.com/labstack/echo"
	gomic "github.com/suzuki-shunsuke/gomic/gomic"
)

type (
	// HelloMock10 is a mock.
	HelloMock10 struct {
		t                      *testing.T
		name                   string
		CallbackNotImplemented func(t *testing.T, intfName, methodName string)
		Impl                   HelloMock10Impl
	}

	// HelloMock10Impl holds functions which implement interface's methods.
	HelloMock10Impl struct {
		Request        func() *http.Request
		SetRequest     func(r *http.Request)
		Response       func() *echo.Response
		IsTLS          func() bool
		IsWebSocket    func() bool
		Scheme         func() string
		RealIP         func() string
		Path           func() string
		SetPath        func(p string)
		Param          func(name string) string
		ParamNames     func() []string
		SetParamNames  func(names ...string)
		ParamValues    func() []string
		SetParamValues func(values ...string)
		QueryParam     func(name string) string
		QueryParams    func() url.Values
		QueryString    func() string
		FormValue      func(name string) string
		FormParams     func() (url.Values, error)
		FormFile       func(name string) (*multipart.FileHeader, error)
		MultipartForm  func() (*multipart.Form, error)
		Cookie         func(name string) (*http.Cookie, error)
		SetCookie      func(cookie *http.Cookie)
		Cookies        func() []*http.Cookie
		Get            func(key string) interface{}
		Set            func(key string, val interface{})
		Bind           func(i interface{}) error
		Validate       func(i interface{}) error
		Render         func(code int, name string, data interface{}) error
		HTML           func(code int, html string) error
		HTMLBlob       func(code int, b []byte) error
		String         func(code int, s string) error
		JSON           func(code int, i interface{}) error
		JSONPretty     func(code int, i interface{}, indent string) error
		JSONBlob       func(code int, b []byte) error
		JSONP          func(code int, callback string, i interface{}) error
		JSONPBlob      func(code int, callback string, b []byte) error
		XML            func(code int, i interface{}) error
		XMLPretty      func(code int, i interface{}, indent string) error
		XMLBlob        func(code int, b []byte) error
		Blob           func(code int, contentType string, b []byte) error
		Stream         func(code int, contentType string, r io.Reader) error
		File           func(file string) error
		Attachment     func(file string, name string) error
		Inline         func(file string, name string) error
		NoContent      func(code int) error
		Redirect       func(code int, url string) error
		Error          func(err error)
		Handler        func() echo.HandlerFunc
		SetHandler     func(h echo.HandlerFunc)
		Logger         func() echo.Logger
		Echo           func() *echo.Echo
		Reset          func(r *http.Request, w http.ResponseWriter)
	}
)

// NewHelloMock10 returns HelloMock10 .
func NewHelloMock10(t *testing.T) *HelloMock10 {
	return &HelloMock10{t: t}
}

// Request is a mock method.
func (mock HelloMock10) Request() *http.Request {
	methodName := "Request" // nolint: goconst
	if mock.Impl.Request != nil {
		return mock.Impl.Request()
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeRequest()
}

// FakeRequest is a fake method.
func (mock HelloMock10) FakeRequest() *http.Request {
	var (
		r0 *http.Request
	)
	return r0
}

// SetRequest is a mock method.
func (mock HelloMock10) SetRequest(r *http.Request) {
	methodName := "SetRequest" // nolint: goconst
	if mock.Impl.SetRequest != nil {
		mock.Impl.SetRequest(r)
		return
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	mock.FakeSetRequest(r)
}

// FakeSetRequest is a fake method.
func (mock HelloMock10) FakeSetRequest(r *http.Request) {
}

// Response is a mock method.
func (mock HelloMock10) Response() *echo.Response {
	methodName := "Response" // nolint: goconst
	if mock.Impl.Response != nil {
		return mock.Impl.Response()
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeResponse()
}

// FakeResponse is a fake method.
func (mock HelloMock10) FakeResponse() *echo.Response {
	var (
		r0 *echo.Response
	)
	return r0
}

// IsTLS is a mock method.
func (mock HelloMock10) IsTLS() bool {
	methodName := "IsTLS" // nolint: goconst
	if mock.Impl.IsTLS != nil {
		return mock.Impl.IsTLS()
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeIsTLS()
}

// FakeIsTLS is a fake method.
func (mock HelloMock10) FakeIsTLS() bool {
	var (
		r0 bool
	)
	return r0
}

// IsWebSocket is a mock method.
func (mock HelloMock10) IsWebSocket() bool {
	methodName := "IsWebSocket" // nolint: goconst
	if mock.Impl.IsWebSocket != nil {
		return mock.Impl.IsWebSocket()
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeIsWebSocket()
}

// FakeIsWebSocket is a fake method.
func (mock HelloMock10) FakeIsWebSocket() bool {
	var (
		r0 bool
	)
	return r0
}

// Scheme is a mock method.
func (mock HelloMock10) Scheme() string {
	methodName := "Scheme" // nolint: goconst
	if mock.Impl.Scheme != nil {
		return mock.Impl.Scheme()
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeScheme()
}

// FakeScheme is a fake method.
func (mock HelloMock10) FakeScheme() string {
	var (
		r0 string
	)
	return r0
}

// RealIP is a mock method.
func (mock HelloMock10) RealIP() string {
	methodName := "RealIP" // nolint: goconst
	if mock.Impl.RealIP != nil {
		return mock.Impl.RealIP()
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeRealIP()
}

// FakeRealIP is a fake method.
func (mock HelloMock10) FakeRealIP() string {
	var (
		r0 string
	)
	return r0
}

// Path is a mock method.
func (mock HelloMock10) Path() string {
	methodName := "Path" // nolint: goconst
	if mock.Impl.Path != nil {
		return mock.Impl.Path()
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakePath()
}

// FakePath is a fake method.
func (mock HelloMock10) FakePath() string {
	var (
		r0 string
	)
	return r0
}

// SetPath is a mock method.
func (mock HelloMock10) SetPath(p string) {
	methodName := "SetPath" // nolint: goconst
	if mock.Impl.SetPath != nil {
		mock.Impl.SetPath(p)
		return
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	mock.FakeSetPath(p)
}

// FakeSetPath is a fake method.
func (mock HelloMock10) FakeSetPath(p string) {
}

// Param is a mock method.
func (mock HelloMock10) Param(name string) string {
	methodName := "Param" // nolint: goconst
	if mock.Impl.Param != nil {
		return mock.Impl.Param(name)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeParam(name)
}

// FakeParam is a fake method.
func (mock HelloMock10) FakeParam(name string) string {
	var (
		r0 string
	)
	return r0
}

// ParamNames is a mock method.
func (mock HelloMock10) ParamNames() []string {
	methodName := "ParamNames" // nolint: goconst
	if mock.Impl.ParamNames != nil {
		return mock.Impl.ParamNames()
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeParamNames()
}

// FakeParamNames is a fake method.
func (mock HelloMock10) FakeParamNames() []string {
	var (
		r0 []string
	)
	return r0
}

// SetParamNames is a mock method.
func (mock HelloMock10) SetParamNames(names ...string) {
	methodName := "SetParamNames" // nolint: goconst
	if mock.Impl.SetParamNames != nil {
		mock.Impl.SetParamNames(names...)
		return
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	mock.FakeSetParamNames(names...)
}

// FakeSetParamNames is a fake method.
func (mock HelloMock10) FakeSetParamNames(names ...string) {
}

// ParamValues is a mock method.
func (mock HelloMock10) ParamValues() []string {
	methodName := "ParamValues" // nolint: goconst
	if mock.Impl.ParamValues != nil {
		return mock.Impl.ParamValues()
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeParamValues()
}

// FakeParamValues is a fake method.
func (mock HelloMock10) FakeParamValues() []string {
	var (
		r0 []string
	)
	return r0
}

// SetParamValues is a mock method.
func (mock HelloMock10) SetParamValues(values ...string) {
	methodName := "SetParamValues" // nolint: goconst
	if mock.Impl.SetParamValues != nil {
		mock.Impl.SetParamValues(values...)
		return
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	mock.FakeSetParamValues(values...)
}

// FakeSetParamValues is a fake method.
func (mock HelloMock10) FakeSetParamValues(values ...string) {
}

// QueryParam is a mock method.
func (mock HelloMock10) QueryParam(name string) string {
	methodName := "QueryParam" // nolint: goconst
	if mock.Impl.QueryParam != nil {
		return mock.Impl.QueryParam(name)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeQueryParam(name)
}

// FakeQueryParam is a fake method.
func (mock HelloMock10) FakeQueryParam(name string) string {
	var (
		r0 string
	)
	return r0
}

// QueryParams is a mock method.
func (mock HelloMock10) QueryParams() url.Values {
	methodName := "QueryParams" // nolint: goconst
	if mock.Impl.QueryParams != nil {
		return mock.Impl.QueryParams()
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeQueryParams()
}

// FakeQueryParams is a fake method.
func (mock HelloMock10) FakeQueryParams() url.Values {
	var (
		r0 url.Values
	)
	return r0
}

// QueryString is a mock method.
func (mock HelloMock10) QueryString() string {
	methodName := "QueryString" // nolint: goconst
	if mock.Impl.QueryString != nil {
		return mock.Impl.QueryString()
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeQueryString()
}

// FakeQueryString is a fake method.
func (mock HelloMock10) FakeQueryString() string {
	var (
		r0 string
	)
	return r0
}

// FormValue is a mock method.
func (mock HelloMock10) FormValue(name string) string {
	methodName := "FormValue" // nolint: goconst
	if mock.Impl.FormValue != nil {
		return mock.Impl.FormValue(name)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeFormValue(name)
}

// FakeFormValue is a fake method.
func (mock HelloMock10) FakeFormValue(name string) string {
	var (
		r0 string
	)
	return r0
}

// FormParams is a mock method.
func (mock HelloMock10) FormParams() (url.Values, error) {
	methodName := "FormParams" // nolint: goconst
	if mock.Impl.FormParams != nil {
		return mock.Impl.FormParams()
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeFormParams()
}

// FakeFormParams is a fake method.
func (mock HelloMock10) FakeFormParams() (url.Values, error) {
	var (
		r0 url.Values
		r1 error
	)
	return r0, r1
}

// FormFile is a mock method.
func (mock HelloMock10) FormFile(name string) (*multipart.FileHeader, error) {
	methodName := "FormFile" // nolint: goconst
	if mock.Impl.FormFile != nil {
		return mock.Impl.FormFile(name)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeFormFile(name)
}

// FakeFormFile is a fake method.
func (mock HelloMock10) FakeFormFile(name string) (*multipart.FileHeader, error) {
	var (
		r0 *multipart.FileHeader
		r1 error
	)
	return r0, r1
}

// MultipartForm is a mock method.
func (mock HelloMock10) MultipartForm() (*multipart.Form, error) {
	methodName := "MultipartForm" // nolint: goconst
	if mock.Impl.MultipartForm != nil {
		return mock.Impl.MultipartForm()
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeMultipartForm()
}

// FakeMultipartForm is a fake method.
func (mock HelloMock10) FakeMultipartForm() (*multipart.Form, error) {
	var (
		r0 *multipart.Form
		r1 error
	)
	return r0, r1
}

// Cookie is a mock method.
func (mock HelloMock10) Cookie(name string) (*http.Cookie, error) {
	methodName := "Cookie" // nolint: goconst
	if mock.Impl.Cookie != nil {
		return mock.Impl.Cookie(name)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeCookie(name)
}

// FakeCookie is a fake method.
func (mock HelloMock10) FakeCookie(name string) (*http.Cookie, error) {
	var (
		r0 *http.Cookie
		r1 error
	)
	return r0, r1
}

// SetCookie is a mock method.
func (mock HelloMock10) SetCookie(cookie *http.Cookie) {
	methodName := "SetCookie" // nolint: goconst
	if mock.Impl.SetCookie != nil {
		mock.Impl.SetCookie(cookie)
		return
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	mock.FakeSetCookie(cookie)
}

// FakeSetCookie is a fake method.
func (mock HelloMock10) FakeSetCookie(cookie *http.Cookie) {
}

// Cookies is a mock method.
func (mock HelloMock10) Cookies() []*http.Cookie {
	methodName := "Cookies" // nolint: goconst
	if mock.Impl.Cookies != nil {
		return mock.Impl.Cookies()
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeCookies()
}

// FakeCookies is a fake method.
func (mock HelloMock10) FakeCookies() []*http.Cookie {
	var (
		r0 []*http.Cookie
	)
	return r0
}

// Get is a mock method.
func (mock HelloMock10) Get(key string) interface{} {
	methodName := "Get" // nolint: goconst
	if mock.Impl.Get != nil {
		return mock.Impl.Get(key)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeGet(key)
}

// FakeGet is a fake method.
func (mock HelloMock10) FakeGet(key string) interface{} {
	var (
		r0 interface{}
	)
	return r0
}

// Set is a mock method.
func (mock HelloMock10) Set(key string, val interface{}) {
	methodName := "Set" // nolint: goconst
	if mock.Impl.Set != nil {
		mock.Impl.Set(key, val)
		return
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	mock.FakeSet(key, val)
}

// FakeSet is a fake method.
func (mock HelloMock10) FakeSet(key string, val interface{}) {
}

// Bind is a mock method.
func (mock HelloMock10) Bind(i interface{}) error {
	methodName := "Bind" // nolint: goconst
	if mock.Impl.Bind != nil {
		return mock.Impl.Bind(i)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeBind(i)
}

// FakeBind is a fake method.
func (mock HelloMock10) FakeBind(i interface{}) error {
	var (
		r0 error
	)
	return r0
}

// Validate is a mock method.
func (mock HelloMock10) Validate(i interface{}) error {
	methodName := "Validate" // nolint: goconst
	if mock.Impl.Validate != nil {
		return mock.Impl.Validate(i)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeValidate(i)
}

// FakeValidate is a fake method.
func (mock HelloMock10) FakeValidate(i interface{}) error {
	var (
		r0 error
	)
	return r0
}

// Render is a mock method.
func (mock HelloMock10) Render(code int, name string, data interface{}) error {
	methodName := "Render" // nolint: goconst
	if mock.Impl.Render != nil {
		return mock.Impl.Render(code, name, data)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeRender(code, name, data)
}

// FakeRender is a fake method.
func (mock HelloMock10) FakeRender(code int, name string, data interface{}) error {
	var (
		r0 error
	)
	return r0
}

// HTML is a mock method.
func (mock HelloMock10) HTML(code int, html string) error {
	methodName := "HTML" // nolint: goconst
	if mock.Impl.HTML != nil {
		return mock.Impl.HTML(code, html)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeHTML(code, html)
}

// FakeHTML is a fake method.
func (mock HelloMock10) FakeHTML(code int, html string) error {
	var (
		r0 error
	)
	return r0
}

// HTMLBlob is a mock method.
func (mock HelloMock10) HTMLBlob(code int, b []byte) error {
	methodName := "HTMLBlob" // nolint: goconst
	if mock.Impl.HTMLBlob != nil {
		return mock.Impl.HTMLBlob(code, b)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeHTMLBlob(code, b)
}

// FakeHTMLBlob is a fake method.
func (mock HelloMock10) FakeHTMLBlob(code int, b []byte) error {
	var (
		r0 error
	)
	return r0
}

// String is a mock method.
func (mock HelloMock10) String(code int, s string) error {
	methodName := "String" // nolint: goconst
	if mock.Impl.String != nil {
		return mock.Impl.String(code, s)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeString(code, s)
}

// FakeString is a fake method.
func (mock HelloMock10) FakeString(code int, s string) error {
	var (
		r0 error
	)
	return r0
}

// JSON is a mock method.
func (mock HelloMock10) JSON(code int, i interface{}) error {
	methodName := "JSON" // nolint: goconst
	if mock.Impl.JSON != nil {
		return mock.Impl.JSON(code, i)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeJSON(code, i)
}

// FakeJSON is a fake method.
func (mock HelloMock10) FakeJSON(code int, i interface{}) error {
	var (
		r0 error
	)
	return r0
}

// JSONPretty is a mock method.
func (mock HelloMock10) JSONPretty(code int, i interface{}, indent string) error {
	methodName := "JSONPretty" // nolint: goconst
	if mock.Impl.JSONPretty != nil {
		return mock.Impl.JSONPretty(code, i, indent)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeJSONPretty(code, i, indent)
}

// FakeJSONPretty is a fake method.
func (mock HelloMock10) FakeJSONPretty(code int, i interface{}, indent string) error {
	var (
		r0 error
	)
	return r0
}

// JSONBlob is a mock method.
func (mock HelloMock10) JSONBlob(code int, b []byte) error {
	methodName := "JSONBlob" // nolint: goconst
	if mock.Impl.JSONBlob != nil {
		return mock.Impl.JSONBlob(code, b)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeJSONBlob(code, b)
}

// FakeJSONBlob is a fake method.
func (mock HelloMock10) FakeJSONBlob(code int, b []byte) error {
	var (
		r0 error
	)
	return r0
}

// JSONP is a mock method.
func (mock HelloMock10) JSONP(code int, callback string, i interface{}) error {
	methodName := "JSONP" // nolint: goconst
	if mock.Impl.JSONP != nil {
		return mock.Impl.JSONP(code, callback, i)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeJSONP(code, callback, i)
}

// FakeJSONP is a fake method.
func (mock HelloMock10) FakeJSONP(code int, callback string, i interface{}) error {
	var (
		r0 error
	)
	return r0
}

// JSONPBlob is a mock method.
func (mock HelloMock10) JSONPBlob(code int, callback string, b []byte) error {
	methodName := "JSONPBlob" // nolint: goconst
	if mock.Impl.JSONPBlob != nil {
		return mock.Impl.JSONPBlob(code, callback, b)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeJSONPBlob(code, callback, b)
}

// FakeJSONPBlob is a fake method.
func (mock HelloMock10) FakeJSONPBlob(code int, callback string, b []byte) error {
	var (
		r0 error
	)
	return r0
}

// XML is a mock method.
func (mock HelloMock10) XML(code int, i interface{}) error {
	methodName := "XML" // nolint: goconst
	if mock.Impl.XML != nil {
		return mock.Impl.XML(code, i)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeXML(code, i)
}

// FakeXML is a fake method.
func (mock HelloMock10) FakeXML(code int, i interface{}) error {
	var (
		r0 error
	)
	return r0
}

// XMLPretty is a mock method.
func (mock HelloMock10) XMLPretty(code int, i interface{}, indent string) error {
	methodName := "XMLPretty" // nolint: goconst
	if mock.Impl.XMLPretty != nil {
		return mock.Impl.XMLPretty(code, i, indent)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeXMLPretty(code, i, indent)
}

// FakeXMLPretty is a fake method.
func (mock HelloMock10) FakeXMLPretty(code int, i interface{}, indent string) error {
	var (
		r0 error
	)
	return r0
}

// XMLBlob is a mock method.
func (mock HelloMock10) XMLBlob(code int, b []byte) error {
	methodName := "XMLBlob" // nolint: goconst
	if mock.Impl.XMLBlob != nil {
		return mock.Impl.XMLBlob(code, b)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeXMLBlob(code, b)
}

// FakeXMLBlob is a fake method.
func (mock HelloMock10) FakeXMLBlob(code int, b []byte) error {
	var (
		r0 error
	)
	return r0
}

// Blob is a mock method.
func (mock HelloMock10) Blob(code int, contentType string, b []byte) error {
	methodName := "Blob" // nolint: goconst
	if mock.Impl.Blob != nil {
		return mock.Impl.Blob(code, contentType, b)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeBlob(code, contentType, b)
}

// FakeBlob is a fake method.
func (mock HelloMock10) FakeBlob(code int, contentType string, b []byte) error {
	var (
		r0 error
	)
	return r0
}

// Stream is a mock method.
func (mock HelloMock10) Stream(code int, contentType string, r io.Reader) error {
	methodName := "Stream" // nolint: goconst
	if mock.Impl.Stream != nil {
		return mock.Impl.Stream(code, contentType, r)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeStream(code, contentType, r)
}

// FakeStream is a fake method.
func (mock HelloMock10) FakeStream(code int, contentType string, r io.Reader) error {
	var (
		r0 error
	)
	return r0
}

// File is a mock method.
func (mock HelloMock10) File(file string) error {
	methodName := "File" // nolint: goconst
	if mock.Impl.File != nil {
		return mock.Impl.File(file)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeFile(file)
}

// FakeFile is a fake method.
func (mock HelloMock10) FakeFile(file string) error {
	var (
		r0 error
	)
	return r0
}

// Attachment is a mock method.
func (mock HelloMock10) Attachment(file string, name string) error {
	methodName := "Attachment" // nolint: goconst
	if mock.Impl.Attachment != nil {
		return mock.Impl.Attachment(file, name)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeAttachment(file, name)
}

// FakeAttachment is a fake method.
func (mock HelloMock10) FakeAttachment(file string, name string) error {
	var (
		r0 error
	)
	return r0
}

// Inline is a mock method.
func (mock HelloMock10) Inline(file string, name string) error {
	methodName := "Inline" // nolint: goconst
	if mock.Impl.Inline != nil {
		return mock.Impl.Inline(file, name)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeInline(file, name)
}

// FakeInline is a fake method.
func (mock HelloMock10) FakeInline(file string, name string) error {
	var (
		r0 error
	)
	return r0
}

// NoContent is a mock method.
func (mock HelloMock10) NoContent(code int) error {
	methodName := "NoContent" // nolint: goconst
	if mock.Impl.NoContent != nil {
		return mock.Impl.NoContent(code)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeNoContent(code)
}

// FakeNoContent is a fake method.
func (mock HelloMock10) FakeNoContent(code int) error {
	var (
		r0 error
	)
	return r0
}

// Redirect is a mock method.
func (mock HelloMock10) Redirect(code int, url string) error {
	methodName := "Redirect" // nolint: goconst
	if mock.Impl.Redirect != nil {
		return mock.Impl.Redirect(code, url)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeRedirect(code, url)
}

// FakeRedirect is a fake method.
func (mock HelloMock10) FakeRedirect(code int, url string) error {
	var (
		r0 error
	)
	return r0
}

// Error is a mock method.
func (mock HelloMock10) Error(err error) {
	methodName := "Error" // nolint: goconst
	if mock.Impl.Error != nil {
		mock.Impl.Error(err)
		return
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	mock.FakeError(err)
}

// FakeError is a fake method.
func (mock HelloMock10) FakeError(err error) {
}

// Handler is a mock method.
func (mock HelloMock10) Handler() echo.HandlerFunc {
	methodName := "Handler" // nolint: goconst
	if mock.Impl.Handler != nil {
		return mock.Impl.Handler()
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeHandler()
}

// FakeHandler is a fake method.
func (mock HelloMock10) FakeHandler() echo.HandlerFunc {
	var (
		r0 echo.HandlerFunc
	)
	return r0
}

// SetHandler is a mock method.
func (mock HelloMock10) SetHandler(h echo.HandlerFunc) {
	methodName := "SetHandler" // nolint: goconst
	if mock.Impl.SetHandler != nil {
		mock.Impl.SetHandler(h)
		return
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	mock.FakeSetHandler(h)
}

// FakeSetHandler is a fake method.
func (mock HelloMock10) FakeSetHandler(h echo.HandlerFunc) {
}

// Logger is a mock method.
func (mock HelloMock10) Logger() echo.Logger {
	methodName := "Logger" // nolint: goconst
	if mock.Impl.Logger != nil {
		return mock.Impl.Logger()
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeLogger()
}

// FakeLogger is a fake method.
func (mock HelloMock10) FakeLogger() echo.Logger {
	var (
		r0 echo.Logger
	)
	return r0
}

// Echo is a mock method.
func (mock HelloMock10) Echo() *echo.Echo {
	methodName := "Echo" // nolint: goconst
	if mock.Impl.Echo != nil {
		return mock.Impl.Echo()
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeEcho()
}

// FakeEcho is a fake method.
func (mock HelloMock10) FakeEcho() *echo.Echo {
	var (
		r0 *echo.Echo
	)
	return r0
}

// Reset is a mock method.
func (mock HelloMock10) Reset(r *http.Request, w http.ResponseWriter) {
	methodName := "Reset" // nolint: goconst
	if mock.Impl.Reset != nil {
		mock.Impl.Reset(r, w)
		return
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	mock.FakeReset(r, w)
}

// FakeReset is a fake method.
func (mock HelloMock10) FakeReset(r *http.Request, w http.ResponseWriter) {
}
