package examples

// Don't edit this file.
// This file is generated by gomic 0.4.0.
// https://github.com/suzuki-shunsuke/gomic

import (
	"os"
	testing "testing"

	gomic "github.com/suzuki-shunsuke/gomic/gomic"
)

type (
	// OSMock is a mock.
	OSMock struct {
		t                      *testing.T
		name                   string
		CallbackNotImplemented gomic.CallbackNotImplemented
		impl                   OSMockImpl
	}

	// OSMockImpl holds functions which implement interface's methods.
	OSMockImpl struct {
		Getwd func() (string, error)
		Mkdir func(name string, perm os.FileMode) error
	}
)

// NewOSMock returns OSMock .
func NewOSMock(t *testing.T, cb gomic.CallbackNotImplemented) *OSMock {
	return &OSMock{t: t, CallbackNotImplemented: cb}
}

// Getwd is a mock method.
func (mock OSMock) Getwd() (string, error) {
	methodName := "Getwd" // nolint: goconst
	if mock.impl.Getwd != nil {
		return mock.impl.Getwd()
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.fakeZeroGetwd()
}

// SetGetwd sets a method and returns the mock.
func (mock *OSMock) SetGetwd(impl func() (string, error)) *OSMock {
	mock.impl.Getwd = impl
	return mock
}

// SetFakeGetwd sets a fake method.
func (mock *OSMock) SetFakeGetwd(r0 string, r1 error) *OSMock {
	mock.impl.Getwd = func() (string, error) {
		return r0, r1
	}
	return mock
}

// fakeZeroGetwd is a fake method which returns zero values.
func (mock OSMock) fakeZeroGetwd() (string, error) {
	var (
		r0 string
		r1 error
	)
	return r0, r1
}

// Mkdir is a mock method.
func (mock OSMock) Mkdir(name string, perm os.FileMode) error {
	methodName := "Mkdir" // nolint: goconst
	if mock.impl.Mkdir != nil {
		return mock.impl.Mkdir(name, perm)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.fakeZeroMkdir(name, perm)
}

// SetMkdir sets a method and returns the mock.
func (mock *OSMock) SetMkdir(impl func(name string, perm os.FileMode) error) *OSMock {
	mock.impl.Mkdir = impl
	return mock
}

// SetFakeMkdir sets a fake method.
func (mock *OSMock) SetFakeMkdir(r0 error) *OSMock {
	mock.impl.Mkdir = func(string, os.FileMode) error {
		return r0
	}
	return mock
}

// fakeZeroMkdir is a fake method which returns zero values.
func (mock OSMock) fakeZeroMkdir(name string, perm os.FileMode) error {
	var (
		r0 error
	)
	return r0
}
