package examples

// Don't edit this file.
// This file is generated by gomic 0.1.1.
// https://github.com/suzuki-shunsuke/gomic

import (
	"os"
	testing "testing"

	gomic "github.com/suzuki-shunsuke/gomic/gomic"
)

type (
	// OSMock is a mock.
	OSMock struct {
		t                      *testing.T
		name                   string
		CallbackNotImplemented gomic.CallbackNotImplemented
		Impl                   OSMockImpl
	}

	// OSMockImpl holds functions which implement interface's methods.
	OSMockImpl struct {
		Getwd func() (string, error)
		Mkdir func(name string, perm os.FileMode) error
	}
)

// NewOSMock returns OSMock .
func NewOSMock(t *testing.T, cb gomic.CallbackNotImplemented) *OSMock {
	return &OSMock{t: t, CallbackNotImplemented: cb}
}

// Getwd is a mock method.
func (mock OSMock) Getwd() (string, error) {
	methodName := "Getwd" // nolint: goconst
	if mock.Impl.Getwd != nil {
		return mock.Impl.Getwd()
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeGetwd()
}

// FakeGetwd is a fake method.
func (mock OSMock) FakeGetwd() (string, error) {
	var (
		r0 string
		r1 error
	)
	return r0, r1
}

// Mkdir is a mock method.
func (mock OSMock) Mkdir(name string, perm os.FileMode) error {
	methodName := "Mkdir" // nolint: goconst
	if mock.Impl.Mkdir != nil {
		return mock.Impl.Mkdir(name, perm)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeMkdir(name, perm)
}

// FakeMkdir is a fake method.
func (mock OSMock) FakeMkdir(name string, perm os.FileMode) error {
	var (
		r0 error
	)
	return r0
}
