package examples

// Don't edit this file.
// This file is generated by gomic 0.1.1.
// https://github.com/suzuki-shunsuke/gomic

import (
	testing "testing"

	gomic "github.com/suzuki-shunsuke/gomic/gomic"
)

type (
	// ReadCloserMock is a mock.
	ReadCloserMock struct {
		t                      *testing.T
		name                   string
		CallbackNotImplemented gomic.CallbackNotImplemented
		Impl                   ReadCloserMockImpl
	}

	// ReadCloserMockImpl holds functions which implement interface's methods.
	ReadCloserMockImpl struct {
		Read  func(p []byte) (n int, err error)
		Close func() error
	}
)

// NewReadCloserMock returns ReadCloserMock .
func NewReadCloserMock(t *testing.T, cb gomic.CallbackNotImplemented) *ReadCloserMock {
	return &ReadCloserMock{t: t, CallbackNotImplemented: cb}
}

// Read is a mock method.
func (mock ReadCloserMock) Read(p []byte) (n int, err error) {
	methodName := "Read" // nolint: goconst
	if mock.Impl.Read != nil {
		return mock.Impl.Read(p)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeRead(p)
}

// FakeRead is a fake method.
func (mock ReadCloserMock) FakeRead(p []byte) (n int, err error) {
	return n, err
}

// Close is a mock method.
func (mock ReadCloserMock) Close() error {
	methodName := "Close" // nolint: goconst
	if mock.Impl.Close != nil {
		return mock.Impl.Close()
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeClose()
}

// FakeClose is a fake method.
func (mock ReadCloserMock) FakeClose() error {
	var (
		r0 error
	)
	return r0
}
