package examples

// Don't edit this file.
// This file is generated by gomic 0.4.0.
// https://github.com/suzuki-shunsuke/gomic

import (
	testing "testing"

	gomic "github.com/suzuki-shunsuke/gomic/gomic"
)

type (
	// ReadCloserMock is a mock.
	ReadCloserMock struct {
		t                      *testing.T
		name                   string
		CallbackNotImplemented gomic.CallbackNotImplemented
		impl                   ReadCloserMockImpl
	}

	// ReadCloserMockImpl holds functions which implement interface's methods.
	ReadCloserMockImpl struct {
		Read  func(p []byte) (n int, err error)
		Close func() error
	}
)

// NewReadCloserMock returns ReadCloserMock .
func NewReadCloserMock(t *testing.T, cb gomic.CallbackNotImplemented) *ReadCloserMock {
	return &ReadCloserMock{t: t, CallbackNotImplemented: cb}
}

// Read is a mock method.
func (mock ReadCloserMock) Read(p []byte) (n int, err error) {
	methodName := "Read" // nolint: goconst
	if mock.impl.Read != nil {
		return mock.impl.Read(p)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.fakeZeroRead(p)
}

// SetRead sets a method and returns the mock.
func (mock *ReadCloserMock) SetRead(impl func(p []byte) (n int, err error)) *ReadCloserMock {
	mock.impl.Read = impl
	return mock
}

// SetFakeRead sets a fake method.
func (mock *ReadCloserMock) SetFakeRead(n int, err error) *ReadCloserMock {
	mock.impl.Read = func(p []byte) (n int, err error) {
		return n, err
	}
	return mock
}

// fakeZeroRead is a fake method which returns zero values.
func (mock ReadCloserMock) fakeZeroRead(p []byte) (n int, err error) {
	return n, err
}

// Close is a mock method.
func (mock ReadCloserMock) Close() error {
	methodName := "Close" // nolint: goconst
	if mock.impl.Close != nil {
		return mock.impl.Close()
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.fakeZeroClose()
}

// SetClose sets a method and returns the mock.
func (mock *ReadCloserMock) SetClose(impl func() error) *ReadCloserMock {
	mock.impl.Close = impl
	return mock
}

// SetFakeClose sets a fake method.
func (mock *ReadCloserMock) SetFakeClose(r0 error) *ReadCloserMock {
	mock.impl.Close = func() error {
		return r0
	}
	return mock
}

// fakeZeroClose is a fake method which returns zero values.
func (mock ReadCloserMock) fakeZeroClose() error {
	var (
		r0 error
	)
	return r0
}
