package test

// Don't edit this file.
// This file is generated by gomic 0.2.1.
// https://github.com/suzuki-shunsuke/gomic

import (
	testing "testing"

	gomic "github.com/suzuki-shunsuke/gomic/gomic"
	test "github.com/suzuki-shunsuke/gomic/internal/domain"
)

type (
	// CfgReaderMock is a mock.
	CfgReaderMock struct {
		t                      *testing.T
		name                   string
		CallbackNotImplemented gomic.CallbackNotImplemented
		Impl                   CfgReaderMockImpl
	}

	// CfgReaderMockImpl holds functions which implement interface's methods.
	CfgReaderMockImpl struct {
		Read func(p0 string) (test.Config, error)
	}
)

// NewCfgReaderMock returns CfgReaderMock .
func NewCfgReaderMock(t *testing.T, cb gomic.CallbackNotImplemented) *CfgReaderMock {
	return &CfgReaderMock{t: t, CallbackNotImplemented: cb}
}

// Read is a mock method.
func (mock CfgReaderMock) Read(p0 string) (test.Config, error) {
	methodName := "Read" // nolint: goconst
	if mock.Impl.Read != nil {
		return mock.Impl.Read(p0)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.FakeRead(p0)
}

// FakeRead is a fake method.
func (mock CfgReaderMock) FakeRead(p0 string) (test.Config, error) {
	var (
		r0 test.Config
		r1 error
	)
	return r0, r1
}
