package test

// Don't edit this file.
// This file is generated by gomic 0.3.0.
// https://github.com/suzuki-shunsuke/gomic

import (
	"io"
	testing "testing"

	gomic "github.com/suzuki-shunsuke/gomic/gomic"
)

type (
	// FileSystemMock is a mock.
	FileSystemMock struct {
		t                      *testing.T
		name                   string
		CallbackNotImplemented gomic.CallbackNotImplemented
		Impl                   FileSystemMockImpl
	}

	// FileSystemMockImpl holds functions which implement interface's methods.
	FileSystemMockImpl struct {
		Exist          func(p0 string) bool
		MkdirAll       func(p0 string) error
		Write          func(p0 string, p1 []byte) error
		GetWriteCloser func(p0 string) (io.WriteCloser, error)
		Getwd          func() (string, error)
	}
)

// NewFileSystemMock returns FileSystemMock .
func NewFileSystemMock(t *testing.T, cb gomic.CallbackNotImplemented) *FileSystemMock {
	return &FileSystemMock{t: t, CallbackNotImplemented: cb}
}

// Exist is a mock method.
func (mock FileSystemMock) Exist(p0 string) bool {
	methodName := "Exist" // nolint: goconst
	if mock.Impl.Exist != nil {
		return mock.Impl.Exist(p0)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.fakeZeroExist(p0)
}

// SetFakeExist sets a fake method.
func (mock *FileSystemMock) SetFakeExist(r0 bool) {
	mock.Impl.Exist = func(p0 string) bool {
		return r0
	}
}

// fakeZeroExist is a fake method which returns zero values.
func (mock FileSystemMock) fakeZeroExist(p0 string) bool {
	var (
		r0 bool
	)
	return r0
}

// MkdirAll is a mock method.
func (mock FileSystemMock) MkdirAll(p0 string) error {
	methodName := "MkdirAll" // nolint: goconst
	if mock.Impl.MkdirAll != nil {
		return mock.Impl.MkdirAll(p0)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.fakeZeroMkdirAll(p0)
}

// SetFakeMkdirAll sets a fake method.
func (mock *FileSystemMock) SetFakeMkdirAll(r0 error) {
	mock.Impl.MkdirAll = func(p0 string) error {
		return r0
	}
}

// fakeZeroMkdirAll is a fake method which returns zero values.
func (mock FileSystemMock) fakeZeroMkdirAll(p0 string) error {
	var (
		r0 error
	)
	return r0
}

// Write is a mock method.
func (mock FileSystemMock) Write(p0 string, p1 []byte) error {
	methodName := "Write" // nolint: goconst
	if mock.Impl.Write != nil {
		return mock.Impl.Write(p0, p1)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.fakeZeroWrite(p0, p1)
}

// SetFakeWrite sets a fake method.
func (mock *FileSystemMock) SetFakeWrite(r0 error) {
	mock.Impl.Write = func(p0 string, p1 []byte) error {
		return r0
	}
}

// fakeZeroWrite is a fake method which returns zero values.
func (mock FileSystemMock) fakeZeroWrite(p0 string, p1 []byte) error {
	var (
		r0 error
	)
	return r0
}

// GetWriteCloser is a mock method.
func (mock FileSystemMock) GetWriteCloser(p0 string) (io.WriteCloser, error) {
	methodName := "GetWriteCloser" // nolint: goconst
	if mock.Impl.GetWriteCloser != nil {
		return mock.Impl.GetWriteCloser(p0)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.fakeZeroGetWriteCloser(p0)
}

// SetFakeGetWriteCloser sets a fake method.
func (mock *FileSystemMock) SetFakeGetWriteCloser(r0 io.WriteCloser, r1 error) {
	mock.Impl.GetWriteCloser = func(p0 string) (io.WriteCloser, error) {
		return r0, r1
	}
}

// fakeZeroGetWriteCloser is a fake method which returns zero values.
func (mock FileSystemMock) fakeZeroGetWriteCloser(p0 string) (io.WriteCloser, error) {
	var (
		r0 io.WriteCloser
		r1 error
	)
	return r0, r1
}

// Getwd is a mock method.
func (mock FileSystemMock) Getwd() (string, error) {
	methodName := "Getwd" // nolint: goconst
	if mock.Impl.Getwd != nil {
		return mock.Impl.Getwd()
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.fakeZeroGetwd()
}

// SetFakeGetwd sets a fake method.
func (mock *FileSystemMock) SetFakeGetwd(r0 string, r1 error) {
	mock.Impl.Getwd = func() (string, error) {
		return r0, r1
	}
}

// fakeZeroGetwd is a fake method which returns zero values.
func (mock FileSystemMock) fakeZeroGetwd() (string, error) {
	var (
		r0 string
		r1 error
	)
	return r0, r1
}
