package domain

// MockTpl is a mock's template.
const MockTpl = `
package {{.PackageName}}

// Don't edit this file.
// This file is generated by gomic {{.Version}}.
// {{.URL}}

import (
{{- range .Imports -}}
  {{- range .}}
	{{.}}
  {{- end}}
{{end -}}
)

type (
	// {{.MockName}} is a mock.
	{{.MockName}} struct {
		t *testing.T
		name string
		callbackNotImplemented gomic.CallbackNotImplemented
		impl struct {
{{- range .Methods}}
				{{.Declaration}}
{{- end}}
		}
	}
)

// New{{.MockName}} returns {{.MockName}} .
func New{{.MockName}}(t *testing.T, cb gomic.CallbackNotImplemented) *{{.MockName}} {
	return &{{.MockName}}{
		t: t, name: "{{.MockName}}", callbackNotImplemented: cb}
}
{{$mockName := .MockName -}}
{{- range .Methods}}
// {{.Name}} is a mock method.
func (mock {{$mockName}}) {{.Name}}{{.Definition}} {
	methodName := "{{.Name}}"  // nolint: goconst
	if mock.impl.{{.Name}} != nil {
{{- if .Results}}
		return mock.impl.{{.Name}}({{.ParamsStr}})
{{- else}}
		mock.impl.{{.Name}}({{.ParamsStr}})
		return
{{- end}}
	}
	if mock.callbackNotImplemented != nil {
		mock.callbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	{{if .Results}}return mock.fakeZero{{.Name}}({{.ParamsStr}}){{end}}
}

// SetFunc{{.Name}} sets a method and returns the mock.
func (mock *{{$mockName}}) SetFunc{{.Name}}(impl func{{.Definition}}) *{{$mockName}} {
	mock.impl.{{.Name}} = impl
	return mock
}

{{if .Results}}
// SetReturn{{.Name}} sets a fake method.
func (mock *{{$mockName}}) SetReturn{{.Name}}{{.SetReturnDefinition}} *{{$mockName}} {
	mock.impl.{{.Name}} = func{{.SetReturnInternalDefinition}} {
		return {{.ResultValuesStr}}
	}
	return mock
}

// fakeZero{{.Name}} is a fake method which returns zero values.
func (mock {{$mockName}}) fakeZero{{.Name}}{{.Definition}} {
  {{- if not .HasResultNames}}
	var (
{{- range .Results}}
		{{.Name}} {{.Type}}
{{- end}}
	)
	{{- end}}
	return {{.ResultValuesStr}}
}
{{end}}
{{end}}
`
