package domain

// MockTpl is a mock's template.
const MockTpl = `
package {{.PackageName}}

// Don't edit this file.
// This file is generated by gomic {{.Version}}.
// {{.URL}}

import (
{{- range .Imports -}}
  {{- range .}}
	{{.}}
  {{- end}}
{{end -}}
)

type (
	// {{.MockName}} is a mock.
	{{.MockName}} struct {
		t *testing.T
		name string
		CallbackNotImplemented gomic.CallbackNotImplemented
		Impl {{.MockName}}Impl
	}

	// {{.MockName}}Impl holds functions which implement interface's methods.
	{{.MockName}}Impl struct {
{{- range .Methods}}
		{{.Declaration}}
{{- end}}
	}
)

// New{{.MockName}} returns {{.MockName}} .
func New{{.MockName}}(t *testing.T, cb gomic.CallbackNotImplemented) *{{.MockName}} {
	return &{{.MockName}}{t: t, CallbackNotImplemented: cb}
}
{{$mockName := .MockName -}}
{{- range .Methods}}
// {{.Name}} is a mock method.
func (mock {{$mockName}}) {{.Definition}} {
	methodName := "{{.Name}}"  // nolint: goconst
	if mock.Impl.{{.Name}} != nil {
{{- if .Results}}
		return mock.Impl.{{.Name}}({{.ParamsStr}})
{{- else}}
		mock.Impl.{{.Name}}({{.ParamsStr}})
		return
{{- end}}
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	{{if .Results}}return {{end}}mock.Fake{{.Name}}({{.ParamsStr}})
}

// Fake{{.Name}} is a fake method.
func (mock {{$mockName}}) Fake{{.Definition}} {
{{- if .Results}}
  {{- if not .HasResultNames}}
	var (
{{- range .Results}}
		{{.Name}} {{.Type}}
{{- end}}
	)
	{{- end}}
	return {{.ResultValuesStr}}
{{- end}}
}
{{end}}
`
